#!/usr/bin/perl

# $Id: ex1e,v 1.3 2005-12-18 16:31:31+11 sh1517 Exp sh1517 $

# $Log: ex1e,v $
# Revision 1.3  2005-12-18 16:31:31+11  sh1517
# 1 After changes to report to supply CGI auth data as white space sep
#   values following the local_cgi data source tag.
#
# Revision 1.2  2005-11-17 19:21:15+11  sh1517
# 1 Only report on hostnames matching the regex argument.
#
# Revision 1.1  2005-10-31 20:18:35+11  sh1517
# Initial revision
#

use strict ;

use Nagios::Report ;

my $hostname_re = shift @ARGV ;
$hostname_re
  or die <<USAGE;
$0 <hostname | hostname_pattern>

Extracts Nagios Availability report data for host(s) matching the regex argument.
eg $0 ^Alb
USAGE

my $host_re = qr/$hostname_re/ 
  or die "Can't compile hostname regex '$hostname_re'." ;

my $x = Nagios::Report->new(q<web_page NagServer AuthUser Pw>, [q<24x7 Optus_DEST_SLA_hours>])
  or die "Can't construct Nagios::Report object." ;


							# Only display these fields in this order.
my @these_fields = qw(
  HOST_NAME
  TOTAL_TIME_DOWN
  PERCENT_TOTAL_TIME_DOWN
  PERCENT_TOTAL_TIME_UP
  AVAIL_URL
) ;

$x->mkreport(
							# Display these fields only (in the order of the list)


		\@these_fields,
							# Record selector


		sub { my %F = @_; my $h = $F{HOST_NAME}; $h =~ /$host_re/ },

							# Sort order

		# sub { my %f = @_; package Nagios::Report; $a->[$f{HOST_NAME}] cmp $b->[$f{HOST_NAME}] }
) ;

$x->debug_dump(290, 4) ;
