#!/usr/bin/perl

# $Id: ex5,v 1.2 2005-12-18 16:47:17+11 sh1517 Exp sh1517 $

# $Log: ex5,v $
# Revision 1.2  2005-12-18 16:47:17+11  sh1517
# 1 Add auth parms to local_cgi data source tag (formerly these
#   had been hard coded in the object).
#
# Revision 1.1  2005-11-08 12:16:05+11  sh1517
# Initial revision
#

use strict ;

use Nagios::Report ;

my $x = Nagios::Report->new(q<local_cgi NagServer AuthUser>)
  or die "Can't construct Nagios::Report object." ;

$x->mkreport(
		[ qw(
			HOST_NAME
			PERCENT_TOTAL_TIME_UP
			TOTAL_TIME_DOWN
			TOTAL_TIME_DOWN_HMS
			TOTAL_TIME_UNREACHABLE
			TOTAL_TIME_UNREACHABLE_HMS
			AVAIL_URL
			TREND_URL
		   )
	       ],

		# sub { 1 },
		sub { my %F = @_; my $u = $F{PERCENT_TOTAL_TIME_UP}; $u =~ s/%//; $u < 100 },

		&comp(alpha => 0, ascend => 0, fields => [qw(TOTAL_TIME_DOWN TOTAL_TIME_UNREACHABLE)]),

		sub {	$_ = shift @_; my %F = @_;
			my $d = $F{TOTAL_TIME_DOWN} ;
			my $u = $F{TOTAL_TIME_UNREACHABLE} ;
			push @$_, 
				&t2hms($d),
				&t2hms($u) ;
			qw(TOTAL_TIME_DOWN_HMS TOTAL_TIME_UNREACHABLE_HMS)
		}
) ;


						# $x->debug_dump ;
$x->excel_dump('/mnt/dest_smb/coms/Comms Data/Availability-month_to_date.xls') ;
# $x->excel_dump();
