#!/usr/bin/perl


use strict ;

use Nagios::Report ;

my $x = Nagios::Report->new(q<local_cgi NagServer AuthUser>, [ qw(24x7) ], 'today')
  or die "Can't construct Nagios::Report object." ;

$x->mkreport(
		[ qw(
			HOST_NAME
			PERCENT_TOTAL_TIME_UP
			TOTAL_TIME_DOWN
			TOTAL_TIME_DOWN_HMS
			TOTAL_TIME_UNREACHABLE
			TOTAL_TIME_UNREACHABLE_HMS
			AVAIL_URL
			TREND_URL
		   )
	       ],

		sub { my %F = @_; my $u = $F{PERCENT_TOTAL_TIME_UP}; $u =~ s/%//; $u < 100 },
		# sub { 1 },

		&comp(alpha => 0, ascend => 0, fields => [qw(TOTAL_TIME_DOWN TOTAL_TIME_UNREACHABLE)]),

		sub {	$_ = shift @_; my %F = @_;
			my $d = $F{TOTAL_TIME_DOWN} ;
			my $u = $F{TOTAL_TIME_UNREACHABLE} ;
			push @$_, 
				&t2hms($d),
				&t2hms($u) ;
			qw(TOTAL_TIME_DOWN_HMS TOTAL_TIME_UNREACHABLE_HMS)
		}
) ;



$x->debug_dump(240, 2) ;
							# 240 chars is needed for the URLs.
