#!/usr/bin/perl

# $Id: ex5e,v 1.3 2005-12-18 16:53:18+11 sh1517 Exp sh1517 $

# $Log: ex5e,v $
# Revision 1.3  2005-12-18 16:53:18+11  sh1517
# 1 Add auth parms to the web_page data source tag (formerly hardcoded in class).
#
# Revision 1.2  2005-11-24 17:45:09+11  sh1517
# 1 Reduce number of fields displayed (making the report far more usable).
#
# Revision 1.1  2005-11-22 16:05:45+11  sh1517
# Initial revision
#

use strict ;

use Nagios::Report ;
use Getopt::Std ;

use vars qw($opt_t) ;

getopt 't' ;

my $usage = <<USAGE ;

$0 -t <timeperiod>

Displays those hosts with less than 100% total time up during the timeperiod.

timeperiod ::= today | yesterday | thisweek | lastweek | thismonth | lastmonth | thisyear | lastyear
               last12hours | last24hours | last7days | last31days

USAGE

die $usage
  unless $opt_t ;

die $usage
  unless $opt_t =~ /^(?:today|yesterday|this(?:week|month|year)|last(?:week|month|year|24hours|12hours|7days|31days))/ ;

my $x = Nagios::Report->new(q<web_page NagServer AuthUser Pw>, [ qw(24x7) ], $opt_t)
  or die "Can't construct Nagios::Report object." ;

$x->mkreport(
		[ qw(
			HOST_NAME
			PERCENT_TOTAL_TIME_UP
			DOWN
			UP
			OUTAGE
		   )
	       ],

		sub { my %F = @_; my $u = $F{PERCENT_TOTAL_TIME_UP}; $u =~ s/%//; $u < 100 },

		&comp(alpha => 0, ascend => 0, fields => [qw(TOTAL_TIME_DOWN TOTAL_TIME_UNREACHABLE)]),

		undef,

		1,
) ;



$x->debug_dump(20) ;
